---
# defaults file for oc-cluster-up
service_catalog: "true"
hawkular_metrics: "false"
use_existing_config: "false"
host_config_dir: "{{playbook_dir}}/../ui"
cluster_image: openshift/origin
cluster_version: "v3.7.1"
cluster_public_ip: "192.168.37.1"
cluster_public_hostname: "{{ cluster_public_ip }}"