galaxy_info:
  author: Aerogear
  description: Setup OpenShift Ansible Broker (OAB) in OpenShift

  issue_tracker_url: https://github.com/aerogear/mobile-core/issues

  license: license (MIT)

  min_ansible_version: 2.2

  platforms:
  - name: macOS
    versions:
    - all
  - name: OSX
    versions:
    - all
  - name: Fedora
    versions:
    - 26
    - 25

  galaxy_tags:
  - aerogear
  - openshift
  - ansible
  - service
  - broker
  - asb

dependencies: []
