---
# tasks file for create-mobile-client-crd

- name: Check for mobileClient CRD
  shell: "oc get customresourcedefinitions"
  register: current_crds

- block:
  - name: Copy CRD definition to tmp file
    copy:
      src: ../files/mobile-client-crd.yaml
      dest: /tmp/mobile-client-crd.yaml  

  - name: Create mobileClient CRD
    shell: "oc create -f /tmp/mobile-client-crd.yaml"

  - name: Create mobile-admin clusterrole
    shell: "oc create clusterrole mobileclient-admin --verb=create,delete,get,list,patch,update,watch --resource=mobileclients"

  - name: Add mobileclient-admin role to authenticated users
    shell: "oc adm policy add-cluster-role-to-group mobileclient-admin system:authenticated"

  when: "'mobileclients.mobile.k8s.io' not in current_crds.stdout"

